### PR TITLE
bug fix for issue #202 and #205

### PR DESCRIPTION
**Pull request by icehong**
This will fix issue #202 and #205 ,  it works on ggg-easy-07.  Hopes it will works on other  tsumego.

### CODE REVIEW

**Comment by icehong** [comment]
For now I don't know how to run spoon testcases on AS,  otherwise I can test others cases.

**Comment by icehong** [comment]
Sorry this commit breaks review sgf function,  maybe I misunderstanding the code.

**Comment by ligi** [comment]
no worries - thanks for trying

**Comment by icehong** [comment]
This patch works fine.  I tried  the code without this patch,  got the same problem with game review function.  
It's must be a new issue on beta version.

**Comment by ligi** [comment]
what error do you see in the game review function?

**Comment by icehong** [comment]
Just can't open sgf file in review mode ,  there is an null access crash on  ligi_wip branch 

04-14 21:49:07.733 15239-15239/org.ligi.gobandroid_hd E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.ligi.gobandroid_hd, PID: 15239
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.ligi.gobandroid_hd/org.ligi.gobandroid_hd.ui.review.GameReviewActivity}: java.lang.IllegalStateException: comments_textview must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3197)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3305)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7428)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.IllegalStateException: comments_textview must not be null
        at org.ligi.gobandroid_hd.ui.fragments.NavigationAndCommentFragment.createView(NavigationAndCommentFragment.kt:23)
        at org.ligi.gobandroid_hd.ui.fragments.GobandroidGameAwareFragment.onCreateView(GobandroidGameAwareFragment.kt:20)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2900)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1339)
        at android.app.Activity.performStart(Activity.java:7392)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3160)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3305) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7428) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by icehong** [comment]
And this .

**Pull request closed without merging**
