### PR TITLE
Issue197 reposition move

### PR DESCRIPTION
**Pull request by gthazmatt**
This PR resolves the issue introduced in my last one. I have included test cases in TheGoGame to verify this.

### CODE REVIEW

**Comment by ligi** [comment]
looks good to me - but will have to look a bit closer before merging. And could this also be a side effect from the last one:
`In tsumego, taken stones with 0 liberties don't disappear, not possible to finish many problems, e.g. Easy #3. Maybe stops working if you backtrack or take hint.`
Just got this via play from a user - but have some other things to do before I can care for this.

**Comment by gthazmatt** [comment]
Almost certainly. That tsumego example helps. I'll check tomorrow if this PR fixes it.

**Comment by ligi** [comment]
Thanks - merging this anyway - looks good to me - love the added tests.

**Comment by gthazmatt** [comment]
I found the issue. I can push a fix and a test case to this branch if you want, although I'm not sure why you closed this when you said you were going to merge it.

**Comment by ligi** [comment]
great - but please wait a second - will merge to master in a second -
but did some rebasing on that branch - so give me a minute

**Comment by ligi** [comment]
Now it is merged

**Comment by ligi** [comment]
Great you found the problem. I am using a new CI currently (https://github.com/ligi/kontinuum) and this one is not yet building the PRs - so I checked it out as a branch so my CI was picking it up and checked it. Please apply your fix on master - be aware that I did some rebasing.

**Pull request closed without merging**
