### PR TITLE
Variations chosen way.

### PR DESCRIPTION
**Pull request by icehong**
Add an variations chosen option in settings and variation window, and default off.

Very glad to hear that you will add me to the credits section, Many Thanks ...   
Learning a lot android programming skill  from this project,  which is my most favorite go APP.  Thanks again. 
My google plus:   https://plus.google.com/u/0/114810044949660525922

### CODE REVIEW

**Comment by ligi** [comment]
:+1:

**Comment by ligi** [comment]
can you check if this is correct: https://github.com/ligi/gobandroid/commit/a2014e0b1f14256e124e10dbf26ba5d2fc5bc4b8

**Comment by icehong** [comment]
Yes ,  The link is correct .

2016-03-22 23:09 GMT+08:00 ligi <notifications@github.com>:

**Comment by ligi** [comment]
I ment more the name - I could verify the link - but I am careful with letters I do not understand -  one wrong copy and paste and you may insult someone ;-)

**Comment by icehong** [comment]
Yes,  Chinese name display very well.   :)

2016-03-22 23:37 GMT+08:00 ligi <notifications@github.com>:

**Comment by ligi** [comment]
I had to rework the settings a bit so that things get more clear - unfortunately this inverted the meaning and I could not invert the chinese texts - so I better removed them - would be great if you could add them again with the adapted meaning.

**Comment by icehong** [comment]
OK  I will add chinese translations later.

2016-03-23 0:00 GMT+08:00 ligi <notifications@github.com>:

**Comment by ligi** [comment]
some user feedback:

> I don't know how recent this has been implemented, but the buttons for scrolling to the left and right seems to have shifted to the left because of the extra variation buttons on the right. As a right hander, this is mighty uncomfortable. Hoping if there could be an option in the settings to invert the left/right layout for both handers. Or an option to remove the variation arrows (which will move the navigation arrows more toward the middle),

**Comment by ildar** [comment]
hm, I disagree with the user. Is he using a narrow screen? If so, it might
be reasonable to move the variant buttons to the next row?

**Comment by ildar** [comment]
BTW, regarding
https://play.google.com/store/apps/details?id=org.ligi.gobandroid_hd&reviewId=Z3A6QU9xcFRPR193QzFPVE1Hc2F6UHd1ZUVNTGtUN0ZkT0R2cDdaYTVReE9CMkhXZlZOcHc5NzB3RVVfTlFoUlA0ZTEwSjFmWlhKQnhJVXJIdGlhOU1xMXZJ
He writes that the variant choice dialog is irritating.
I'd answer him that there's an option in settings.

**Comment by ildar** [comment]
In Russian: можно выключить в Настройках.

**Comment by ligi** [comment]
thanks for the info - I updated the comment in google-play.
Regarding a second row - this will be really bad for users with phones that dont have a lot of height - you already have a small comment region there - this might vanish completely then if you make 2 rows for the buttons

**Comment by ildar** [comment]
Oh, I see. The user just needs to get used to the new button layout, that's
all.

**Pull request merged**
